on: push
jobs:
 build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node app.js
      - name: push changes to remote
      - run: |
        git config --global user.name "robertmaugerglobant"
        git config --global user.email "robert.mauger@globant.com"
        git add &lt;public/assets/css/&gt; git commit -m "commit message"
        git push
