on: push
jobs:
 build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node app.js
      - git config --global --add safe.directory /__w/demo/demo
      - uses: stefanzweifel/git-auto-commit-action@v5
