on:
  push:
    branches:
      - figmaTempMain
jobs:
 build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: yarn add -D sass
      - run: npm install
      - run: npm install -g style-dictionary
      - run: npm run build
      - run: git config --global --add safe.directory /__w/demo/demo
      - uses: stefanzweifel/git-auto-commit-action@v5
