on:
  push:
    branches:
      - figmaTempMain
jobs:
 build-node:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: rm -v tokens/Components/button/demo.json
      - run: 'rm -rf  tokens/color/Brand\ Mid.json'
      - run: rm -v tokens/color/Brand\ Mid.json
      - run: rm -v tokens/color/"Brand Dim Alt.json"
      - run: rm -v tokens/color/"Brand Dim.json"
      - run: rm -v tokens/color/"Primary Base.json"
      - run: npm install -D style-dictionary
      - run: style-dictionary init basic
      - run: style-dictionary build
      - run: git config --global --add safe.directory /__w/demo/demo
      - uses: stefanzweifel/git-auto-commit-action@v5
